"""
Nickname reverse mapping for email template encoding.

Note:
    This is no longer used in tokenization, only in feature engineering.
"""

NICKNAME_MAP = {
    "alexander": {"alex"},
    "andrew": {"andy"},
    "anne": {"annie", "nancy"},
    "arthur": {"art"},
    "benjamin": {"ben"},
    "william": {"bill", "will"},
    "robert": {"bob", "bobby", "rob"},
    "catherine": {"cathy"},
    "charles": {"charlie", "chuck"},
    "daniel": {"dan", "danny"},
    "david": {"dave"},
    "donald": {"don"},
    "edward": {"ed", "eddie"},
    "elizabeth": {"eliza", "liz", "liza"},
    "eleanor": {"ellie"},
    "francis": {"frank"},
    "frederick": {"fred"},
    "gerald": {"gary", "jerry"},
    "gregory": {"greg"},
    "harold": {"harry", "hal"},
    "john": {"jack", "johnny"},
    "jacob": {"jake"},
    "janet": {"jan"},
    "jeffrey": {"jeff"},
    "jennifer": {"jen", "jenny"},
    "james": {"jim", "jimmy"},
    "joseph": {"joe", "joey", "jody"},
    "jonathan": {"jon"},
    "joshua": {"josh"},
    "joy": {"joyce"},
    "judith": {"judy"},
    "katherine": {"kate", "kathy"},
    "kenneth": {"ken"},
    "lawrence": {"larry"},
    "lewis": {"lou"},
    "margaret": {"maggie", "marge"},
    "martin": {"marty"},
    "matthew": {"matt"},
    "megan": {"meg"},
    "melvin": {"mel"},
    "michael": {"mike"},
    "nicholas": {"nick"},
    "patrick": {"pat"},
    "peter": {"pete"},
    "philip": {"phil"},
    "richard": {"rick", "rich"},
    "ronald": {"ron"},
    "samuel": {"sam"},
    "steven": {"steve"},
    "susan": {"sue"},
    "theodore": {"ted"},
    "terence": {"terry"},
    "timothy": {"tim"},
    "thomas": {"tom"},
    "anthony": {"tony"},
    "victor": {"vic"},
    "zachary": {"zack", "zak"},
    "nastya": {"nastia"},
    "bill": {"william"},
    "douglas": {"doug"},
    "doug": {"douglas"},
    "mitch": {"mitchell"},
    "mitchell": {"mitch"},
    "wesley": {"wes"},
    "patricia": {"tricia"},
    "rajiv": {"raj"},
}
